### ISSUE TITLE
An item with the same key has already been added. Key: Id

### ISSUE THREAD

**Issue by vitalybibikov** [sdrapkin/SecurityDriven.TinyORM#6]
Using from Azure Functions v2
version: 1.2.7067.20307
TF: netcoreapp2.2
Microsoft.NET.Sdk.Functions:1.0.28

![image](https://user-images.githubusercontent.com/7008739/57979619-179e2a00-7a29-11e9-9001-ceb4f1e50f03.png)

I've removed out of scope DI, and queryParams as it still throws the error:

`
  var query = "SELECT * FROM loyalty.Venue v " +
                        "JOIN loyalty.Worker w ON v.Id = w.VenueId " +
                        "JOIN loyalty.Location l ON l.VenueId = v.Id " +
                        "WHERE v.IsArchived = 0 AND w.WorkerId = " + $"'{request.UserId.ToString()}'";

            var con = DbContext.Create(connectionString);
            var row = (await con.QueryAsync(query), cancellationToken);
`

Result: An item with the same key has already been added. Key: Id

Looks like when multiple tables are joined and they have duplicated column names (Id), it fails in adding them into dictionary.

**Comment by sdrapkin** [comment]
@vitalybibikov This is by design, for 2 reasons - conceptual and practical.

Conceptually, TinyORM aims for safe, defensive, hard-to-misuse APIs. Supporting multiple same-name columns would often lead to developer bugs, and thus should be avoided since it creates ambiguity. Every column should have a distinct name.

Practically, it's problematic to populate a Dictionary<name,value> when you have duplicate names, and also to try to unambiguously materialize a POCO with multiple values matching the same property name.

Dapper decided to always use the last-encountered value. TinyORM throws.

**Comment by vitalybibikov** [comment]
In a real world apps, it's hardly possible to have unique names for all columns in every table.
As well as not to have JOINs.

Id - for PK is a common practice.
IsArchived - common thing for soft-delete
Created,Modified and others for Auditing

You can also have some common fields like - Approved, Validated. 
If it is something related to multi-tenancy we can also have additional properties as well.

All these things are the same in many and many apps and dbs.
Renaming them in queries leads to ambiguity and error prone. Moreover it is time wasteful.

**Comment by sdrapkin** [comment]
@vitalybibikov In real world apps, using `select *` queries is highly inadvisable. The correct approach is not to "have unique names for all columns in every table", but to have smart projections with explicitly-named columns for each field in the projection. As I explained, unique names for returned schema is how every micro-orm deals with this, including TinyORM. Entity Framework also throws "duplicate column name" exception.
